### ISSUE TITLE
Brainly.getData is not a function

### ISSUE THREAD

**Issue by MFarelS** [elianiva/brainly-scraper-ts#1]
### Code
```
const Brainly = require("brainly-scraper-ts")

Brainly.getData("kenapa manusia bernafas?").then(res => console.log(res))
```

### Error
```
C:\Users\RELFAIZ\Music\brainly>node .
C:\Users\RELFAIZ\Music\brainly\index.js:3
Brainly.getData("kenapa manusia bernafas?").then(res => console.log(res))
        ^

TypeError: Brainly.getData is not a function
    at Object.<anonymous> (C:\Users\RELFAIZ\Music\brainly\index.js:3:9)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m
```

# ScreenShoot
![C__Users_RELFAIZ_Music_brainly_index js (media,  github, lib) - Sublime Text (UNREGISTERED) 24_06_2021 17_24_30](https://user-images.githubusercontent.com/58540890/123247976-98398980-d511-11eb-9599-deb49c2ddfda.png)

![Command Prompt 24_06_2021 17_31_21](https://user-images.githubusercontent.com/58540890/123248084-bacba280-d511-11eb-869e-8dccd95224e0.png)

**Comment by elianiva** [comment]
```javascript
const Brainly = require("brainly-scraper-ts").default
```

**Comment by MFarelS** [comment]
> ```js
> const Brainly = require("brainly-scraper-ts").default
> ```

Okeh
